name: Sync upstream fork

env:
  UPSTREAM_URL: "https://github.com/Million-Token-Community/million-discord-bot.git"
  TARGET_BRANCH: "main"
on:
  schedule:
  # pull from upstream every day at midnight
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  sync-fork:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: deployment
      - name: Set upstream
        run: git remote add upstream ${{ env.UPSTREAM_URL }}

      - name: Set email
        run: git config --local user.email "tran.peter08@com"

      - name: Set username
        run: git config --local user.name "tranpeter08"

      - name: Pull upstream
        run: git pull upstream ${{env.TARGET_BRANCH}} --allow-unrelated-histories

      - name: Push changes 
        run: git push 
